In [1]:
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from textblob import Word
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
def clean_str(string):
    string = re.sub(r"\'s", "", string)
    string = re.sub(r"\'ve", "", string)
    string = re.sub(r"n\'t", "", string)
    string = re.sub(r"\'re", "", string)
    string = re.sub(r"\'d", "", string)
    string = re.sub(r"\'ll", "", string)
    string = re.sub(r",", "", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", "", string)
    string = re.sub(r"\)", "", string)
    string = re.sub(r"\?", "", string)
    string = re.sub(r"'", "", string)
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"[0-9]\w+|[0-9]","", string)
    string = re.sub(r"\s{2,}", " ", string)
    return string.strip().lower()

In [3]:
data = pd.read_csv('dataset/dataset.csv', encoding = "ISO-8859-1")
#x = data['news'].encode('utf-8').strip()
#y = data['type'].tolist()
#f    = open("dataset/dataset.csv","rb")
#text = f.read().decode(errors='replace')
#contents = text.rstrip("\n")
#contents = text.split("\r\n")

In [4]:
x = data['news'].tolist()
y = data['type'].tolist()

In [5]:
for index,value in enumerate(x):
    print ("processing data:",index)
    x[index] = ' '.join([Word(word).lemmatize() for word in clean_str(value).split()])


processing data: 0
processing data: 1
processing data: 2
processing data: 3
processing data: 4
processing data: 5
processing data: 6
processing data: 7
processing data: 8
processing data: 9
processing data: 10
processing data: 11
processing data: 12
processing data: 13
processing data: 14
processing data: 15
processing data: 16
processing data: 17
processing data: 18
processing data: 19
processing data: 20
processing data: 21
processing data: 22
processing data: 23
processing data: 24
processing data: 25
processing data: 26
processing data: 27
processing data: 28
processing data: 29
processing data: 30
processing data: 31
processing data: 32
processing data: 33
processing data: 34
processing data: 35
processing data: 36
processing data: 37
processing data: 38
processing data: 39
processing data: 40
processing data: 41
processing data: 42
processing data: 43
processing data: 44
processing data: 45
processing data: 46
processing data: 47
processing data: 48
processing data: 49
processing

processing data: 480
processing data: 481
processing data: 482
processing data: 483
processing data: 484
processing data: 485
processing data: 486
processing data: 487
processing data: 488
processing data: 489
processing data: 490
processing data: 491
processing data: 492
processing data: 493
processing data: 494
processing data: 495
processing data: 496
processing data: 497
processing data: 498
processing data: 499
processing data: 500
processing data: 501
processing data: 502
processing data: 503
processing data: 504
processing data: 505
processing data: 506
processing data: 507
processing data: 508
processing data: 509
processing data: 510
processing data: 511
processing data: 512
processing data: 513
processing data: 514
processing data: 515
processing data: 516
processing data: 517
processing data: 518
processing data: 519
processing data: 520
processing data: 521
processing data: 522
processing data: 523
processing data: 524
processing data: 525
processing data: 526
processing da

processing data: 924
processing data: 925
processing data: 926
processing data: 927
processing data: 928
processing data: 929
processing data: 930
processing data: 931
processing data: 932
processing data: 933
processing data: 934
processing data: 935
processing data: 936
processing data: 937
processing data: 938
processing data: 939
processing data: 940
processing data: 941
processing data: 942
processing data: 943
processing data: 944
processing data: 945
processing data: 946
processing data: 947
processing data: 948
processing data: 949
processing data: 950
processing data: 951
processing data: 952
processing data: 953
processing data: 954
processing data: 955
processing data: 956
processing data: 957
processing data: 958
processing data: 959
processing data: 960
processing data: 961
processing data: 962
processing data: 963
processing data: 964
processing data: 965
processing data: 966
processing data: 967
processing data: 968
processing data: 969
processing data: 970
processing da

processing data: 1316
processing data: 1317
processing data: 1318
processing data: 1319
processing data: 1320
processing data: 1321
processing data: 1322
processing data: 1323
processing data: 1324
processing data: 1325
processing data: 1326
processing data: 1327
processing data: 1328
processing data: 1329
processing data: 1330
processing data: 1331
processing data: 1332
processing data: 1333
processing data: 1334
processing data: 1335
processing data: 1336
processing data: 1337
processing data: 1338
processing data: 1339
processing data: 1340
processing data: 1341
processing data: 1342
processing data: 1343
processing data: 1344
processing data: 1345
processing data: 1346
processing data: 1347
processing data: 1348
processing data: 1349
processing data: 1350
processing data: 1351
processing data: 1352
processing data: 1353
processing data: 1354
processing data: 1355
processing data: 1356
processing data: 1357
processing data: 1358
processing data: 1359
processing data: 1360
processing

processing data: 1727
processing data: 1728
processing data: 1729
processing data: 1730
processing data: 1731
processing data: 1732
processing data: 1733
processing data: 1734
processing data: 1735
processing data: 1736
processing data: 1737
processing data: 1738
processing data: 1739
processing data: 1740
processing data: 1741
processing data: 1742
processing data: 1743
processing data: 1744
processing data: 1745
processing data: 1746
processing data: 1747
processing data: 1748
processing data: 1749
processing data: 1750
processing data: 1751
processing data: 1752
processing data: 1753
processing data: 1754
processing data: 1755
processing data: 1756
processing data: 1757
processing data: 1758
processing data: 1759
processing data: 1760
processing data: 1761
processing data: 1762
processing data: 1763
processing data: 1764
processing data: 1765
processing data: 1766
processing data: 1767
processing data: 1768
processing data: 1769
processing data: 1770
processing data: 1771
processing

processing data: 2217
processing data: 2218
processing data: 2219
processing data: 2220
processing data: 2221
processing data: 2222
processing data: 2223
processing data: 2224


In [6]:
vect = TfidfVectorizer(stop_words='english',min_df=2)
X = vect.fit_transform(x)
Y = np.array(y)

In [8]:
data.head()

news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

In [9]:
x

['china had role in yukos split up china lent russia to help the russian government renationalise the key yuganskneftegas unit of oil group yukos it ha been revealed the kremlin said on tuesday that the which russian state bank veb lent state owned rosneft to help buy yugansk in turn came from chinese bank the revelation came a the russian government said rosneft had signed a long term oil supply deal with china the deal see rosneft receive in credit from china cnpc according to russian newspaper vedomosti these credit would be used to pay off the loan rosneft received to finance the purchase of yugansk report said cnpc had been offered of yugansk in return for providing finance but the company opted for a long term oil supply deal instead analyst said one factor that might have influenced the chinese decision wa the possibility of litigation from yukos yugansk former owner if cnpc had become a shareholder rosneft and veb declined to comment the two company rosneft and cnpc have agreed

In [41]:
import nltk

In [42]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\DELL
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [7]:
print ("no of features extracted:",X.shape[1])

no of features extracted: 14788


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [9]:
print ("train size:", X_train.shape)
print ("test size:", X_test.shape)

train size: (1780, 14788)
test size: (445, 14788)


In [16]:
model = RandomForestClassifier(n_estimators=300, max_depth=150,n_jobs=1)
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=150, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [17]:
y_pred = model.predict(X_test)
c_mat = confusion_matrix(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)

In [25]:
print ("Confusion Matrix:\n", c_mat)
print ("\nAccuracy: ",acc)

Confusion Matrix:
 [[111   0   2   1   1]
 [  2  68   1   0   1]
 [  3   0  73   0   0]
 [  0   0   0 102   0]
 [  3   1   1   3  72]]

Accuracy:  0.9573033707865168


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

In [11]:
logreg = LogisticRegression()
rfe = RFE(logreg, 20)
rfe = rfe.fit(X_train, y_train)
#print(rfe.support_)
#print(rfe.ranking_)

In [13]:
y_pre = rfe.predict(X_test)
c_ma = confusion_matrix(y_test,y_pre)
accu = accuracy_score(y_test,y_pre)

In [14]:
print ("Confusion Matrix:\n", c_ma)
print ("\nAccuracy: ",accu)

Confusion Matrix:
 [[89  1  8 17  0]
 [ 3 37  0 32  0]
 [ 7  0 58 11  0]
 [ 2  0  0 99  1]
 [12  3  2 14 49]]

Accuracy:  0.7460674157303371


In [19]:
def check_news_type(news_article):  
    news_article = [' '.join([Word(word).lemmatize() for word in clean_str(news_article).split()])]
    features = vect.transform(news_article)
    return str(model.predict(features)[0])

In [18]:
article = """Android Q isn't likely to debut anytime before the next I/O developer conference later in May. But before the formal announcement of the new Android iteration, a Google device with codename "Coral" has been spotted on Geekbench. The new device, which appears to be the successor to the existing Pixel 3 ₹ 57,419 models, is listed with a Qualcomm SoC that could be the Snapdragon 855, along with 6GB of RAM. There is also an explicit mentioning of Android Q - the next version after Android Pie.

According to the listing on the Geekbench website, as spotted by PhoneArena, the Google Coral device runs Android Q. There is also a section highlighting a Qualcomm SoC. This could be the top-of-the-line, Snapdragon 855 SoC with eight cores featuring a base frequency of 1.78GHz.

The device also has 6GB of RAM. Google was criticised for offering merely 4GB RAM on the existing Pixel 3 and Pixel 3 XL ₹ 69,825 handsets, while the competition majorly brought 6GB and 8GB RAM options. Therefore, a RAM with a capacity of 6GB would be fair enough for the successor to the Pixel 3 family.

The Geekbench listing also shows that the mysterious Google device has received a single-core score of 3,296 and a multi-core score of 9,235. Notably, the benchmark results were published on January 24. This shows that these are too fresh to judge the authenticity of the hardware.

That being said, the listed hardware is quite likely to be a part of the 2019 Pixel lineup that will run Android Q out-of-the-box - considering the history of Pixel devices. The new Android version could come with new notification gestures and have a list of privacy controls. A couple of recent reports also hinted at a system-wide dark mode and a dedicated desktop mode.

"""

In [20]:
check_news_type(article)

'entertainment'

In [21]:
article1='''
A clinical India beat New Zealand by seven wickets in the second T20 International at Auckland on Friday.
'''

In [22]:
check_news_type(article1)

'sport'

In [32]:
from sklearn import tree

In [33]:
ct=tree.DecisionTreeClassifier()

In [34]:
ct=ct.fit(X_train, y_train)

In [35]:
y_pre = ct.predict(X_test)
c_ma = confusion_matrix(y_test,y_pre)
accu = accuracy_score(y_test,y_pre)

In [36]:
print ("Confusion Matrix:\n", c_ma)
print ("\nAccuracy: ",accu)

Confusion Matrix:
 [[92  5  9  3  6]
 [ 3 59  4  5  1]
 [ 7  1 63  3  2]
 [ 6  1  4 90  1]
 [ 6  4  3  1 66]]

Accuracy:  0.8314606741573034


In [37]:
import graphviz 
dot_data = tree.export_graphviz(ct, out_file=None,   
                     filled=True, rounded=True,  
                     special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render("News Classification") 

ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'News Classification'], make sure the Graphviz executables are on your systems' PATH

In [15]:
y_train

array(['sport', 'tech', 'sport', ..., 'politics', 'politics',
       'entertainment'], dtype='<U13')